# Generated by Django 4.2.7 on 2025-10-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chatbot Configuration', 'verbose_name_plural': 'Chatbot Configurations'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AlterField(
            model_name='chatbotconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
